# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Documents\Python\PyQt\SQLite\form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(800, 600)
        Main.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget = QtWidgets.QTabWidget(Main)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tabLive = QtWidgets.QWidget()
        self.tabLive.setObjectName("tabLive")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabLive)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 791, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.boxLive = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.boxLive.setContentsMargins(0, 0, 0, 0)
        self.boxLive.setObjectName("boxLive")
        self.tabWidget.addTab(self.tabLive, "")
        self.tabAnalyse = QtWidgets.QWidget()
        self.tabAnalyse.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabAnalyse.setObjectName("tabAnalyse")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabAnalyse)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 791, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.boxAnalyse = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.boxAnalyse.setContentsMargins(10, 0, 0, 0)
        self.boxAnalyse.setObjectName("boxAnalyse")
        self.boxButtonsAnalyse = QtWidgets.QHBoxLayout()
        self.boxButtonsAnalyse.setObjectName("boxButtonsAnalyse")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkT5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkT5.setObjectName("checkT5")
        self.horizontalLayout.addWidget(self.checkT5)
        self.checkT4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkT4.setObjectName("checkT4")
        self.horizontalLayout.addWidget(self.checkT4)
        self.checkT3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkT3.setObjectName("checkT3")
        self.horizontalLayout.addWidget(self.checkT3)
        self.checkT2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkT2.setObjectName("checkT2")
        self.horizontalLayout.addWidget(self.checkT2)
        self.checkT1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkT1.setObjectName("checkT1")
        self.horizontalLayout.addWidget(self.checkT1)
        self.boxButtonsAnalyse.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnUpdate = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout_3.addWidget(self.btnUpdate)
        self.boxButtonsAnalyse.addLayout(self.verticalLayout_3)
        self.boxAnalyse.addLayout(self.boxButtonsAnalyse)
        self.boxPlotAnalyse = QtWidgets.QVBoxLayout()
        self.boxPlotAnalyse.setObjectName("boxPlotAnalyse")
        self.boxAnalyse.addLayout(self.boxPlotAnalyse)
        self.tabWidget.addTab(self.tabAnalyse, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Main)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLive), _translate("Main", "Live mode"))
        self.checkT5.setText(_translate("Main", "Thermocouple 5"))
        self.checkT4.setText(_translate("Main", "Thermocouple 4"))
        self.checkT3.setText(_translate("Main", "Thermocouple 3"))
        self.checkT2.setText(_translate("Main", "Thermocouple 2"))
        self.checkT1.setText(_translate("Main", "Thermocouple 1"))
        self.btnUpdate.setText(_translate("Main", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalyse), _translate("Main", "Analyse mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Main", "Page"))

